import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, collection, getDocs, getDoc, doc, updateDoc, setDoc, serverTimestamp, query, orderBy, addDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { getStorage, ref as storageRef, uploadBytes, getDownloadURL, deleteObject } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";

// app.js-এর একই Firebase config এখানে বসান।

const firebaseConfig = {
  apiKey: "AIzaSyC_-mRgfZS9oAuG1w3HzyXJJhylurfi3e4",
  authDomain: "smart-digital-bd.firebaseapp.com",
  projectId: "smart-digital-bd",
  storageBucket: "smart-digital-bd.firebasestorage.app",
  messagingSenderId: "1062207066369",
  appId: "1:1062207066369:web:bf1f5eb2129a471a694b00",
  measurementId: "G-BPCRCCJTZR"
};
const configured = firebaseConfig.apiKey !== "PASTE_YOUR_FIREBASE_API_KEY" && firebaseConfig.projectId !== "PASTE_YOUR_PROJECT_ID";
const loginBox=document.getElementById('loginBox'), dashboard=document.getElementById('dashboard');
const loginMessage=document.getElementById('loginMessage'), adminMessage=document.getElementById('adminMessage'), list=document.getElementById('ordersList');
let auth, db, storage;
if(configured){try{const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);storage=getStorage(app);onAuthStateChanged(auth, async user=>{if(user && user.uid==='4lm1ZhfL1WRbdmeLbRezks6W4lQ2'){loginBox.classList.add('hidden');dashboard.classList.remove('hidden');await loadOrders();await loadAdminProducts();}else{dashboard.classList.add('hidden');loginBox.classList.remove('hidden');if(user){loginMessage.textContent='এই অ্যাকাউন্টের অ্যাডমিন অনুমতি নেই।';}}});}catch(err){console.error('Firebase initialization error:',err.code,err.message);loginMessage.textContent='Firebase চালু হয়নি: '+(err.code||err.message||'unknown error');}}else{loginMessage.textContent='প্রথমে admin.js ও app.js-এ একই Firebase config বসান।';}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!auth){loginMessage.textContent='Firebase চালু হয়নি। পেজ রিফ্রেশ করুন; সমস্যা থাকলে কনফিগারেশন পরীক্ষা করুন।';return;}loginMessage.textContent='লগইন হচ্ছে...';try{await signInWithEmailAndPassword(auth,document.getElementById('email').value.trim(),document.getElementById('password').value);loginMessage.textContent='লগইন সফল।';}catch(err){console.error('Firebase Login Error:',err.code,err.message);const messages={'auth/invalid-credential':'ইমেইল বা পাসওয়ার্ড ভুল।','auth/invalid-email':'ইমেইল ঠিক নয়।','auth/user-not-found':'এই ইমেইলে Firebase user নেই।','auth/wrong-password':'পাসওয়ার্ড ভুল।','auth/too-many-requests':'অনেকবার চেষ্টা হয়েছে; কিছুক্ষণ পরে আবার চেষ্টা করুন।','auth/unauthorized-domain':'Firebase Authentication → Settings → Authorized domains-এ smart-digital-bd.onrender.com যোগ করুন।','auth/operation-not-allowed':'Firebase Authentication-এ Email/Password চালু করুন।','auth/network-request-failed':'ইন্টারনেট সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।'};loginMessage.textContent='লগইন সমস্যা ('+(err.code||'unknown')+'): '+(messages[err.code]||err.message||'অজানা সমস্যা');}});
document.getElementById('logoutBtn').addEventListener('click',()=>signOut(auth));
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const labels={pending:'অপেক্ষমাণ',accepted:'অ্যাকসেপ্ট হয়েছে',rejected:'রিজেক্ট হয়েছে'};
async function loadOrders(){list.innerHTML='';adminMessage.textContent='অর্ডার লোড হচ্ছে...';try{const snap=await getDocs(query(collection(db,'orders'),orderBy('createdAt','desc')));if(snap.empty){adminMessage.textContent='এখনও কোনো অর্ডার নেই।';return;}adminMessage.textContent=`মোট ${snap.size}টি অর্ডার`;
snap.forEach(d=>{const o=d.data();const card=document.createElement('article');card.className='order-card';
// ★ নতুন: order.html থেকে আসা quantity/city/address/email আগে অ্যাডমিন প্যানেলে দেখাতই না —
//   ফলে গ্রাহক ঠিকানা দিলেও সেটা হারিয়ে যেত। এখন সব তথ্য দেখা যাবে।
const waNum=String(o.phone||'').replace(/[^0-9]/g,'');const waLink=waNum?`https://wa.me/88${waNum.startsWith('0')?waNum.slice(1):waNum}`:'';
const extra=[];if(o.email)extra.push(`<p><b>ইমেইল:</b> ${esc(o.email)}</p>`);if(o.quantity)extra.push(`<p><b>পরিমাণ:</b> ${esc(o.quantity)}</p>`);if(o.city)extra.push(`<p><b>শহর/জেলা:</b> ${esc(o.city)}</p>`);if(o.address)extra.push(`<p><b>ঠিকানা:</b> ${esc(o.address)}</p>`);if(o.source)extra.push(`<p><b>কোথা থেকে:</b> ${esc(o.source)}</p>`);
card.innerHTML=`<h3>${esc(o.product)}</h3><p><b>অর্ডার আইডি:</b> ${esc(d.id)}</p><p><b>নাম:</b> ${esc(o.name)}</p><p><b>ফোন:</b> ${esc(o.phone)}${waLink?` — <a href="${esc(waLink)}" target="_blank" rel="noopener">WhatsApp</a>`:''}</p><p><b>বিস্তারিত:</b> ${esc(o.details||'—')}</p>${extra.length?`<div class="order-extra">${extra.join('')}</div>`:''}<p><b>অবস্থা:</b> ${esc(labels[o.status]||o.status||'অজানা')}</p><div class="order-actions"><button class="accept" data-status="accepted">অ্যাকসেপ্ট</button><button class="reject" data-status="rejected">রিজেক্ট</button></div>`;
card.querySelectorAll('button[data-status]').forEach(btn=>btn.addEventListener('click',()=>setStatus(d.id,btn.dataset.status)));list.appendChild(card);});
}catch(e){console.error(e);adminMessage.textContent='অর্ডার লোড হয়নি। Firebase Auth, Admin UID ও Firestore Rules পরীক্ষা করুন।';}}
async function setStatus(id,status){if(!confirm(`অর্ডারটি ${labels[status]} করবেন?`))return;try{await updateDoc(doc(db,'orders',id),{status,updatedAt:serverTimestamp()});const orderSnap=await getDoc(doc(db,'orders',id));await setDoc(doc(db,'orderStatus',id),{uid:orderSnap.exists()?(orderSnap.data().uid||''):'',status,updatedAt:serverTimestamp()},{merge:true});adminMessage.textContent='অর্ডারের অবস্থা আপডেট হয়েছে।';await loadOrders();}catch(e){console.error(e);alert('স্ট্যাটাস বদলানো যায়নি। Rules-এ আপনার Admin UID সঠিক আছে কি না দেখুন।');}}

// Product/service management. Products are public-read and admin-write in Firestore Rules.
const productForm=document.getElementById('productForm');
const productMessage=document.getElementById('productMessage');
const adminProducts=document.getElementById('adminProducts');
const val=id=>document.getElementById(id)?.value?.trim()||'';
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function loadAdminProducts(){if(!adminProducts||!db)return;adminProducts.innerHTML='<p>পণ্য লোড হচ্ছে...</p>';try{const snap=await getDocs(query(collection(db,'products'),orderBy('position','asc')));if(snap.empty){adminProducts.innerHTML='<p class="muted">এখনো কোনো পণ্য যোগ করা হয়নি। নিচের ফর্ম থেকে প্রথম পণ্য যোগ করুন।</p>';return;}adminProducts.innerHTML='';snap.forEach(d=>{const x=d.data(),el=document.createElement('article');el.className='order-card';el.innerHTML=`<div class="product-admin-row">${x.imageUrl?`<img src="${escapeHtml(x.imageUrl)}" alt="">`:'<div style="width:76px;height:76px;border-radius:12px;background:#edf1f7;display:grid;place-items:center;font-size:28px">📦</div>'}<div class="meta"><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.category||'অন্যান্য')} · ৳${escapeHtml(x.price)} · ক্রম ${escapeHtml(x.position)}</p><p>${escapeHtml(x.description||'বিবরণ নেই')}</p>${x.fileUrl?`<a href="${escapeHtml(x.fileUrl)}" target="_blank" rel="noopener">ডেলিভারি ফাইল দেখুন</a>`:''}</div><button class="danger-btn" data-delete="${d.id}">মুছুন</button></div>`;el.querySelector('[data-delete]').addEventListener('click',()=>removeProduct(d.id,x));adminProducts.appendChild(el);});}catch(e){console.error(e);adminProducts.innerHTML='<p>পণ্য লোড হয়নি। Firestore Rules ও Index পরীক্ষা করুন।</p>';}}
async function uploadOptionalFile(file,path){if(!file)return '';const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const ref=storageRef(storage,`${path}/${Date.now()}_${safe}`);await uploadBytes(ref,file,{contentType:file.type||'application/octet-stream'});return await getDownloadURL(ref);}
if(productForm){productForm.addEventListener('submit',async e=>{e.preventDefault();if(!auth?.currentUser||auth.currentUser.uid!=='4lm1ZhfL1WRbdmeLbRezks6W4lQ2'){productMessage.textContent='শুধু অনুমোদিত অ্যাডমিন পণ্য যোগ করতে পারবেন।';return;}const name=val('productName'),category=val('productCategory'),price=Number(val('productPrice')),position=Number(val('productPosition'));if(!name||!category||!Number.isFinite(price)||price<0||!Number.isInteger(position)||position<1){productMessage.textContent='নাম, ক্যাটাগরি, সঠিক মূল্য ও ক্রম দিন।';return;}const btn=document.getElementById('saveProductBtn');btn.disabled=true;productMessage.textContent='পণ্য ও ফাইল আপলোড হচ্ছে...';try{const imageFile=document.getElementById('productImage').files[0],deliveryFile=document.getElementById('productFile').files[0];let imageUrl=val('productImageUrl');if(imageFile){if(!imageFile.type.startsWith('image/'))throw new Error('ছবির ফাইল সঠিক নয়।');if(imageFile.size>8*1024*1024)throw new Error('ছবির সাইজ ৮ MB-এর কম রাখুন।');imageUrl=await uploadOptionalFile(imageFile,'products/images');}let fileUrl='';if(deliveryFile){if(deliveryFile.size>14*1024*1024)throw new Error('ডেলিভারি ফাইল ১৪ MB-এর কম রাখুন।');fileUrl=await uploadOptionalFile(deliveryFile,'products/files');}await addDoc(collection(db,'products'),{name,category,price,position,description:val('productDescription'),imageUrl,fileUrl,featured:document.getElementById('productFeatured').checked,active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.uid});productMessage.textContent='সফলভাবে পণ্য যোগ হয়েছে! ওয়েবসাইটে দেখানোর জন্য পেজ রিফ্রেশ করুন।';productForm.reset();document.getElementById('productPosition').value='1';await loadAdminProducts();}catch(err){console.error(err);productMessage.textContent='পণ্য যোগ হয়নি: '+(err.message||err.code||'Firebase Storage/Firestore সেটিংস পরীক্ষা করুন।');}finally{btn.disabled=false;}});document.getElementById('resetProductBtn').addEventListener('click',()=>{productForm.reset();document.getElementById('productPosition').value='1';productMessage.textContent='';});}
async function removeProduct(id,item){if(!confirm('এই পণ্যটি ওয়েবসাইট থেকে মুছে ফেলবেন?'))return;try{await deleteDoc(doc(db,'products',id));await loadAdminProducts();productMessage.textContent='পণ্য মুছে ফেলা হয়েছে।';}catch(e){console.error(e);productMessage.textContent='পণ্য মুছতে পারেনি। Firestore Rules পরীক্ষা করুন।';}}
