import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, onAuthStateChanged, signOut, updateProfile } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, collection, getDocs, query, where } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyC_-mRgfZS9oAuG1w3HzyXJJhylurfi3e4",authDomain:"smart-digital-bd.firebaseapp.com",projectId:"smart-digital-bd",storageBucket:"smart-digital-bd.firebasestorage.app",messagingSenderId:"1062207066369",appId:"1:1062207066369:web:bf1f5eb2129a471a694b00",measurementId:"G-BPCRCCJTZR"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let mode='register';
const authBox=document.getElementById('authBox'),dashboard=document.getElementById('dashboard'),authForm=document.getElementById('authForm'),authMessage=document.getElementById('authMessage');
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function setMode(next){mode=next;document.getElementById('authTitle').textContent=mode==='register'?'নতুন অ্যাকাউন্ট তৈরি করুন':'কাস্টমার লগইন';document.getElementById('authSubmit').textContent=mode==='register'?'রেজিস্ট্রেশন':'লগইন';document.getElementById('switchMode').textContent=mode==='register'?'আগে অ্যাকাউন্ট আছে? লগইন':'নতুন অ্যাকাউন্ট? রেজিস্ট্রেশন';document.getElementById('customerName').parentElement.classList.toggle('hidden',mode==='login');document.getElementById('customerPassword').autocomplete=mode==='login'?'current-password':'new-password';}
document.getElementById('switchMode').addEventListener('click',()=>setMode(mode==='register'?'login':'register'));
authForm.addEventListener('submit',async e=>{e.preventDefault();authMessage.textContent='অপেক্ষা করুন...';const email=document.getElementById('customerEmail').value.trim(),password=document.getElementById('customerPassword').value,name=document.getElementById('customerName').value.trim();try{if(mode==='register'){const cred=await createUserWithEmailAndPassword(auth,email,password);if(name)await updateProfile(cred.user,{displayName:name});authMessage.textContent='অ্যাকাউন্ট তৈরি হয়েছে।';}else{await signInWithEmailAndPassword(auth,email,password);authMessage.textContent='লগইন সফল।';}}catch(e){const msgs={'auth/email-already-in-use':'এই ইমেইলে আগে থেকেই অ্যাকাউন্ট আছে—লগইন করুন।','auth/invalid-email':'ইমেইল ঠিকভাবে লিখুন।','auth/weak-password':'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।','auth/invalid-credential':'ইমেইল বা পাসওয়ার্ড ভুল।','auth/operation-not-allowed':'Firebase Console-এ Email/Password চালু করুন।','auth/unauthorized-domain':'Firebase Authentication → Settings → Authorized domains-এ smart-digital-bd.onrender.com যোগ করুন।','auth/network-request-failed':'ইন্টারনেট সংযোগ পরীক্ষা করুন।'};authMessage.textContent=msgs[e.code]||('সমস্যা হয়েছে: '+e.message);}});
document.getElementById('logoutBtn').addEventListener('click',()=>signOut(auth));
onAuthStateChanged(auth,async user=>{if(!user){authBox.classList.remove('hidden');dashboard.classList.add('hidden');return;}authBox.classList.add('hidden');dashboard.classList.remove('hidden');document.getElementById('profileName').textContent=user.displayName||'নাম দেওয়া হয়নি';document.getElementById('profileEmail').textContent=user.email||'—';document.getElementById('profileUid').textContent=user.uid;await loadOrders(user.uid);});
async function loadOrders(uid){const out=document.getElementById('customerOrders'),msg=document.getElementById('ordersMessage');out.innerHTML='';msg.textContent='অর্ডার লোড হচ্ছে...';try{const snap=await getDocs(query(collection(db,'orders'),where('uid','==',uid)));if(snap.empty){msg.textContent='এখনও আপনার কোনো অর্ডার নেই।';return;}msg.textContent=`আপনার মোট ${snap.size}টি অর্ডার`;const labels={pending:'অপেক্ষমাণ',accepted:'Approved — অ্যাকসেপ্ট হয়েছে',rejected:'Rejected — রিজেক্ট হয়েছে'};const docs=snap.docs.slice().sort((a,b)=>(b.data().createdAt?.seconds||0)-(a.data().createdAt?.seconds||0));docs.forEach(d=>{const o=d.data(),card=document.createElement('article');card.className='customer-order';card.innerHTML=`<h3>${escapeHtml(o.product||'অর্ডার')}</h3><p><b>অর্ডার আইডি:</b> ${escapeHtml(d.id)}</p><p><b>নাম:</b> ${escapeHtml(o.name)}</p><p><b>ফোন:</b> ${escapeHtml(o.phone)}</p><p><b>বিস্তারিত:</b> ${escapeHtml(o.details||'—')}</p><p><b>স্ট্যাটাস:</b> <span class="status">${escapeHtml(labels[o.status]||o.status||'অজানা')}</span></p>`;out.appendChild(card);});}catch(e){console.error(e);msg.textContent='অর্ডার লোড হয়নি। Firestore Rules ও Firebase index পরীক্ষা করুন।';}}
setMode('register');
